### PR TITLE
fix: matching fail won’t fallback bug, resolve #147

### LINKED ISSUE #147: Can't match some path
Cannot match the following path
```
rocket.Get("A/B/C", ...)
rocket.Get("A/*", ...)
```
when user request URL as `A/B`, it cannot match to `A/*`.

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by dannypsnl** [comment]
@shana0440 you could review it now

**Comment by dannypsnl** [comment]
Benchmark compare, I can accept this result
```
benchmark                                        old ns/op     new ns/op     delta
BenchmarkRequest/WithoutUserDefinedContext-2     1554          1559          +0.32%
BenchmarkRequest/WithUserDefinedContext-2        2547          2569          +0.86%
BenchmarkRequest/WithCustomResponse-2            2137          2143          +0.28%
BenchmarkRequest/WithHeader-2                    2410          2427          +0.71%
benchmark                                        old allocs     new allocs     delta
BenchmarkRequest/WithoutUserDefinedContext-2     11             11             +0.00%
BenchmarkRequest/WithUserDefinedContext-2        21             21             +0.00%
BenchmarkRequest/WithCustomResponse-2            14             14             +0.00%
BenchmarkRequest/WithHeader-2                    19             19             +0.00%
benchmark                                        old bytes     new bytes     delta
BenchmarkRequest/WithoutUserDefinedContext-2     928           928           +0.00%
BenchmarkRequest/WithUserDefinedContext-2        1296          1296          +0.00%
BenchmarkRequest/WithCustomResponse-2            1336          1336          +0.00%
BenchmarkRequest/WithHeader-2                    1232          1232          +0.00%
```

File: router.go [hunk 1]
```diff
@@ -6,118 +6,112 @@ import (
...
-		return nil
+	if r.variableRoute != nil {
+		if handler := r.variableRoute.getHandler(restRequestUrl, method); handler != nil {
+			return handler
+		}
 	}
-	if h, ok := next.Handlers[method]; ok {
-		return h
+	if r.wildcardRoute != nil {
+		if h, hasPathRouteHandler := r.wildcardRoute[method]; hasPathRouteHandler {
```
Comment (shana0440) [inline router.go]: `hasPathRouteHandler` should rename to `hasWildcardRouteHandler`
