### PR TITLE
(#126) fix: resolve #126 by checking handler exist or not

### LINKED ISSUE #126: [Bug] Duplicate route won't panic
Following code won't panic:
```go
r := rocket.Get("/", ...)
rocket.Ignite(":80").
    Mount("/", r, r)
```

### PR DESCRIPTION
**Pull request by dannypsnl**

### CODE REVIEW

**Comment by dannypsnl** [comment]
@shana0440 do you have any requirement for this PR? If not then I just merge it.

File: rocket_test.go [hunk 1]
```diff
@@ -0,0 +1,20 @@
+package rocket_test
+
+import (
+	"testing"
+
+	"github.com/dannypsnl/rocket"
+)
+
+func TestDuplicateRoutePanic(t *testing.T) {
```
Comment (shana0440) [inline rocket_test.go]: I think this test is hard to understand because you cannot saw the `/` been mounted twice in this test case.
but I think this problem is because our test is the mess now. we should open a new issue to deal with this.

File: router.go [hunk 2]
```diff
@@ -6,6 +6,10 @@ import (
 	"strings"
 )
 
+var (
+	PanicDuplicateRoute = "Duplicate Route"
```
Comment (shana0440) [inline router.go]: I think we should create a new file put this constant variable.

File: rocket_test.go (hunk 1 above)
Comment (dannypsnl) [reply rocket_test.go]: So what should I do for the test?

Comment (shana0440) [reply rocket_test.go]: nothing for now, I will open a new issue and give an example.
